services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3002:3002
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
